export interface LookupFee {
  code: string;
  name: string;
  type: number;
  value: number;
  method: number;
  type__code: string;
  method__code: string;
}

export interface LookupApplication {
  id: number;
  code: string;
  loanapp__code: string | null;
  status: number;
  status__name: string;
  loan_amount: number;
  loan_term: number;
  approve_amount: number | null;
  approve_term: number | null;
  note: string | null;
  fullname: string;
  phone: string;
  province: string | null;
  district: string | null;
  address: string | null;
  legal_code: string;
  legal_type: number;
  legal_type__code: string;
  legal_type__name: string;
  issue_date: string | null;
  issue_place: string | null;
  sex: number | null;
  sex__name: string | null;
  customer: number;
  customer__code: string;
  product: number;
  product__type__name: string;
  product__type__code: string;
  product__category__name: string;
  product__category__code: string;
  branch: number;
  branch__code: string;
  country: number;
  country__code: string;
  country__name: string;
  currency: number;
  currency__code: string;
  collaborator: number | null;
  source: number | null;
  source__name: string | null;
  creator: number;
  updater: number | null;
  approver: number | null;
  approver__fullname: string | null;
  creator__fullname: string;
  updater__fullname: string | null;
  create_time: string;
  update_time: string;
}

export interface LookupLoan {
  id: number;
  code: string;
  status: number;
  deleted: boolean;
  disbursement: number;
  amount_given: number;
  outstanding: number;
  outstanding_local: number;
  disbursement_local: number;
  principal: number;
  ratio: number;
  rate: number;
  rate_info: string;
  penalty_ratio: number;
  interest_amount: number | null;
  revenue: number | null;
  penalty_amount: number | null;
  itr_income: number;
  fee_income: number;
  due_amount: number;
  due_amount_local: number;
  due_date: string;
  due_days: number;
  valid_from: string;
  valid_to: string;
  batch_date: string;
  beneficiary_account: string | null;
  beneficiary_bank: string | null;
  fees: LookupFee[];
  // principal schedule
  prin_pay_type: number;
  prin_num_cycle: number;
  prin_pay_cycle: number;
  prin_ovd_cycle: number;
  prin_cycle_days: number | null;
  prin_cycle_month: number;
  prin_first_date: string | null;
  prin_last_date: string | null;
  prin_last_amount: number | null;
  prin_next_date: string | null;
  prin_next_amount: number | null;
  prin_ovd_days: number | null;
  prin_ovd: number | null;
  prin_penalty: number | null;
  prin_collected: number | null;
  // interest schedule
  itr_pay_type: number;
  itr_num_cycle: number;
  itr_pay_cycle: number;
  itr_ovd_cycle: number;
  itr_cycle_days: number | null;
  itr_cycle_month: number;
  itr_first_date: string | null;
  itr_last_date: string | null;
  itr_last_amount: number | null;
  itr_next_date: string | null;
  itr_next_amount: number | null;
  itr_ovd_days: number | null;
  itr_ovd: number | null;
  itr_penalty: number | null;
  itr_collected: number | null;
  // fee schedule
  fee_pay_cycle: number;
  fee_num_cycle: number;
  fee_ovd_cycle: number;
  fee_cycle_days: number | null;
  fee_cycle_month: number;
  fee_first_date: string | null;
  fee_last_date: string | null;
  fee_last_amount: number | null;
  fee_next_date: string | null;
  fee_next_amount: number | null;
  fee_ovd_days: number | null;
  fee_ovd: number | null;
  fee_penalty: number | null;
  fee_collected: number | null;
  customer: number;
  product: number;
  branch: number;
  application: number;
  dbm_entry: number | null;
  creator: number;
  updater: number | null;
  approver: number | null;
  prin_last_date_null?: null;
  create_time: string;
  update_time: string;
  approve_time: string | null;
}

export interface LookupCollateral {
  // from Loan_Collateral
  id: number;
  loan: number;
  collateral: number;
  collateral__code: string;
  collateral__type__name: string;
  collateral__type__category__name: string;
  collat_value: number;
  mortgage_value: number;
  collateral__status__name: string | null;
  collateral__warehouse__name: string | null;
  collateral__storage__name: string | null;
  // from Collateral detail
  code: string;
  deleted: boolean;
  appraisal_value: number | null;
  market_value: number | null;
  origin_value: number | null;
  year_mfg: number | null;
  color: string | null;
  vehicle_number: string | null;
  engine_number: string | null;
  seri_number: string | null;
  area: number | null;
  chip: string | null;
  ram: string | null;
  screen: string | null;
  pin: string | null;
  disk: string | null;
  weight: number | null;
  detail: string | null;
  issue_date: string | null;
  issue_time: string | null;
  valid_to: string | null;
  input_date: string | null;
  output_date: string | null;
  sale_date: string | null;
  sale_amount: number | null;
  sale_note: string | null;
  buyer_name: string | null;
  buyer_phone: string | null;
  buyer_address: string | null;
  storage_fee: number | null;
  storage_days: number | null;
  fee_per_day: number | null;
  type: number;
  status: number;
  storage: number | null;
  warehouse: number | null;
  branch: number;
  ownership: number | null;
  currency: number;
  customer: number;
  creator: number;
  updater: number | null;
  create_time: string;
  update_time: string;
}

export interface LookupCustomer {
  id: number;
  code: string;
  fullname: string;
  phone: string;
  email: string | null;
  dob: string | null;
  legal_code: string;
  issued_place: string | null;
  issued_date: string | null;
  province: string | null;
  district: string | null;
  address: string | null;
  note: string | null;
  zalo: string | null;
  facebook: string | null;
  deleted: boolean;
  sex: number | null;
  legal_type: number;
  country: number;
  company: number | null;
  branch: number;
  collaborator: number | null;
  creator: number;
  updater: number | null;
  user: number | null;
  create_time: string;
  update_time: string;
}

export interface LookupResponse {
  application: LookupApplication;
  loan: LookupLoan;
  collateral: LookupCollateral | null;
  customer: LookupCustomer | null;
}
